version: '3.4'

services:
  workhive.server:
    image: ${DOCKER_REGISTRY-}workhiveserver
    build:
      context: .
      dockerfile: src/WorkHive.Server/Dockerfile
    networks:
        - mynetwork

  postgres_image:
      image: postgres:latest
      ports:
        - "5432"
      restart: always
      volumes:
        - db_volume:/var/lib/postgresql/data
        - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
      environment:
        POSTGRES_USER: "bloguser"
        POSTGRES_PASSWORD: "bloguser"
        POSTGRES_DB: "blogdb"
      networks:
        - mynetwork
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
       - mynetwork
volumes:
  db_volume:
networks:
  mynetwork:
     driver: bridge

